name: PeggyCoyle
favicon: null
layout_spectrum: 0.5923325244802982
typography_spectrum: 0.7339037621859461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.755995208863169
  lightness: 0.25357668776996434
  saturation: 0.7055665792431682
  rhythmicContrast: 0.8856407864950597
purpose: []
