name: PeggyCoyle
favicon: null
layout_spectrum: 0.51169
typography_spectrum: 0.24191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0000'
    - '#000000'
    - '#525252'
    - '#df6a6a'
    - '#bcbcbc'
  brandStrength: 0.755995208863169
  lightness: 0.25357668776996434
  saturation: 0.7055665792431682
  rhythmicContrast: 0.8856407864950597
purpose: []
